In [15]:
import pandas as pd
from pandas import DataFrame, Series
import numpy as np
import matplotlib.pyplot as plt
import datetime
import random

%matplotlib inline

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer, TfidfTransformer

from sklearn.pipeline import Pipeline
from sklearn.grid_search import GridSearchCV
from sklearn.preprocessing import StandardScaler, label_binarize, MaxAbsScaler
from sklearn.cross_validation import train_test_split

import sklearn.metrics as skm
from sklearn.metrics import roc_curve, auc

from scipy import interp

from nltk import word_tokenize
from nltk.stem.snowball import SnowballStemmer

from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [17]:
df = pd.read_csv('../data/Consumer_Complaints_with_Consumer_Complaint_Narratives.csv')

# Create 'df_text' for text modeling

In [18]:
def create_df_text(df):
    df_text = pd.DataFrame()  # Create empty df to fill
    
    df_text['Consumer complaint narrative'] = df['Consumer complaint narrative']
    
    cust_resp_dict ={'Closed':0,
                 'Untimely response':0,
                 'Closed with explanation':1,
                 'Closed with non-monetary relief':2,
                 'Closed with monetary relief':2}
    
    df_text['Company response to consumer'] = df['Company response to consumer'].apply(lambda x: cust_resp_dict[x])
    
    return df_text

In [19]:
create_df_text(df).head()

Consumer complaint narrative  \
0  Received Capital One charge card offer XXXX. A...   
1  I do n't know how they got my cell number. I t...   
2  I 'm a longtime member of Charter One Bank/RBS...   
3  After looking at my credit report, I saw a col...   
4  I received a call from a XXXX XXXX from XXXX @...   

   Company response to consumer  
0                             1  
1                             1  
2                             1  
3                             2  
4                             1

# Using Text Features

In [20]:
def prep_text_data(df):
    from sklearn.preprocessing import StandardScaler, label_binarize, MaxAbsScaler
#     print df.head()
    y_ = df['Company response to consumer']
    y = label_binarize(y_, classes = [0, 1, 2])
    n_classes=3
#     y = y.sum(axis=1)
    df.pop('Company response to consumer')
    X = df.values

    print X.shape, y.shape
    print y
    return X, y

In [21]:
df_text = create_df_text(df)
X, y = prep_text_data(df_text)

(84466, 1) (84466, 3)
[[0 1 0]
 [0 1 0]
 [0 1 0]
 ..., 
 [0 1 0]
 [0 1 0]
 [0 0 1]]


In [22]:
def train_test_split_function(X, y):
    from sklearn.cross_validation import train_test_split

    X_train, X_test, y_train, y_test = train_test_split(X,
                                                        y,
                                                        test_size=0.3,
                                                        random_state=11)
    
#     scaler = StandardScaler()
#     scaler.fit(X_train)
#     X_train = scaler.transform(X_train)
#     X_test = scaler.transform(X_test)
#     from sklearn.utils import shuffle
#     X_shuf, Y_shuf = shuffle(X_transformed, Y)


    vectorizer = TfidfVectorizer(stop_words='english',lowercase=True, min_df=0.001, max_df = 0.2)
    X_train = vectorizer.fit_transform(X_train)
    X_test = vectorizer.transform(X_test
                                 )
    return X_train, X_test, y_train, y_test

In [23]:
X_train, X_test, y_train, y_test = train_test_split_function(X, y)

AttributeError: 'numpy.ndarray' object has no attribute 'lower'